server:
  port: 8081

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://101.43.239.43:8300/eureka/ #Eureka地址

spring:
  application:
    name: 3x-mng
  servlet:
    multipart:
      max-file-size: 20MB #设置单个文件最大长度
      max-request-size: 100MB #最大请求文件的大小
  task:
    execution:
      thread-name-prefix: 3x-thread-task-
      pool:
        core-size: 50
        max-size: 200
        keep-alive: 20s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.4.43:3306/3xdb?&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Yyl@4012


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  config: classpath:config/logback-spring.xml